//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatVeXeKhach08
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int MethodID { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
